#!/bin/sh
# Harvest the PVE seam evidence from the vendored git checkouts in docs/third_party/.
#
# This is the counterpart to extract-pve-source.sh, which reads the same
# evidence out of a .deb inside an installer ISO. Both write a block per
# [PVE-F-nnn] entry in docs/pve-facts.md, in the same format, so the two can be
# diffed against each other:
#
#   ISO harvest       what a running Proxmox VE host actually has installed
#   source harvest    what upstream git says, at a commit anyone can check out
#
# The ISO is the authority when they disagree — a fact is about the machine
# proxmod runs on, not about master. The source harvest exists because it needs
# no ISO, it can be re-run by anyone, and it reaches files the .deb does not
# ship separately (every www/manager6/*.js is concatenated into pvemanagerlib.js
# by the time it is packaged, so line references only exist here).
#
# Usage: ./scripts/harvest-pve-src.sh [output-dir]     (default: docs/facts)

set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
TP="$ROOT/docs/third_party"
OUTDIR=${1:-$ROOT/docs/facts}

die() { echo "harvest-pve-src: $*" >&2; exit 1; }

[ -d "$TP/pve-manager/www/manager6" ] \
    || die "docs/third_party/ is empty or incomplete; run 'make submodules' first"

mkdir -p "$OUTDIR"
out="$OUTDIR/pve-src.txt"

# The pin. Every line reference below is only meaningful against these commits,
# so they go in the header and get regenerated with the file.
sha() { git -C "$TP/$1" rev-parse HEAD 2>/dev/null || echo '(unknown)'; }

M="$TP/pve-manager"
W="$M/www/manager6"

# grep -n against a path, or a loud marker if the pattern has gone. A silent
# empty block is the one outcome worth ruling out: it reads identically to
# "this fact is fine" while meaning "the code we depend on has moved".
gone() { echo "!! NOT FOUND: $1"; }
find_in() {
    _f=$1; _what=$2; _pat=$3
    if [ ! -f "$_f" ]; then gone "$_f (file missing) - $_what"; return; fi
    grep -nE "$_pat" "$_f" || gone "$_what in ${_f#"$ROOT"/}"
}

{
    echo "# proxmod PVE fact harvest (from source)"
    echo "# generated by scripts/harvest-pve-src.sh from docs/third_party/"
    echo "#"
    echo "# Pinned commits — every line number below is relative to these:"
    for r in pve-manager pve-common pve-http-server proxmox-widget-toolkit \
             pve-access-control qemu-server pve-container pve-storage; do
        [ -d "$TP/$r" ] && printf '#   %-24s %s\n' "$r" "$(sha "$r")"
    done
    echo "#"
    echo "# Each block is raw evidence for a [PVE-F-nnn] entry in"
    echo "# docs/pve-facts.md. Regenerate after moving a submodule pin and diff,"
    echo "# to see exactly which of our assumptions moved."
    echo

    echo "=== [PVE-F-002] pveproxy/pvedaemon run under taint mode (-T) ==="
    for d in pveproxy pvedaemon pvestatd; do
        printf '%s: ' "$d"
        head -1 "$M/bin/$d" 2>/dev/null || gone "$M/bin/$d"
    done
    echo

    echo "=== [PVE-F-005] pve-manager reloads the daemons from its own postinst ==="
    find_in "$M/debian/postinst" "the daemon reload path" \
        "reload-or-try-restart|pve-ssl\.pem|proxmox_install_mode|^ *triggered\)"
    echo

    echo "=== [PVE-F-010] pve-manager uses dpkg triggers (our precedent) ==="
    cat "$M/debian/triggers" 2>/dev/null || echo "(no triggers file)"
    echo

    echo "=== [PVE-F-020] the index-render seam in PVE::Service::pveproxy ==="
    # shellcheck disable=SC2016 # the $ are Perl sigils we are grepping for
    find_in "$M/PVE/Service/pveproxy.pm" "the get_index seam" \
        "sub get_index|pages *=>|dirs *=>|'/' *=>|index\.html\.tpl|template->process|HTTP::Response->new"
    echo

    echo "=== [PVE-F-021] index.html.tpl script order (our injection anchor) ==="
    find_in "$M/www/index.html.tpl" "the script block" "<script|</head>"
    echo

    echo "=== [PVE-F-022] the four templates get_index can serve ==="
    # shellcheck disable=SC2016 # the $ are Perl sigils we are grepping for
    find_in "$M/PVE/Service/pveproxy.pm" "the template dispatch" \
        '\$basedirs->\{(manager|novnc|xtermjs|yew_mobile)\}|\$dir = '
    echo

    echo "=== [PVE-F-024] the pages/dirs routing tables ==="
    # shellcheck disable=SC2016 # the $ are Perl sigils we are grepping for
    find_in "$TP/pve-http-server/src/PVE/APIServer/AnyEvent.pm" "the routing tables" \
        '\$self->\{pages\}|\$self->\{dirs\}'
    echo

    echo "=== [PVE-F-025] add_dirs walks the tree with File::Find ==="
    find_in "$TP/pve-http-server/src/PVE/APIServer/AnyEvent.pm" "add_dirs" \
        'sub add_dirs|File::Find::dir|find\(\{'
    echo

    echo "=== [PVE-F-026] Content-Length is recomputed from the body ==="
    find_in "$TP/pve-http-server/src/PVE/APIServer/AnyEvent.pm" "the Content-Length recompute" \
        'content_length = length|Content-Length" =>'
    echo

    # ---- the ExtJS config panel. Everything below only exists as separate
    # files here; in a packaged PVE it has been concatenated into
    # pvemanagerlib.js, which is why the ISO harvest can only offer offsets.

    echo "=== [PVE-F-030] ExtJS hook-host classes available to override ==="
    for f in dc/Config.js node/Config.js qemu/Config.js lxc/Config.js \
             storage/Browser.js pool/Config.js sdn/Browser.js sdn/NetworkBrowser.js; do
        [ -f "$W/$f" ] || { gone "$W/$f"; continue; }
        printf '%s\n' "manager6/$f:"
        grep -nE "Ext\.define\('PVE\.|^ *alias: |^ *extend: " "$W/$f" | head -4
    done
    echo

    echo "=== [PVE-F-031] insertNodes, the tab-insertion entry point ==="
    find_in "$W/panel/ConfigPanel.js" "insertNodes and the initComponent order" \
        "insertNodes|me\.callParent\(\)|me\.savedItems = |delete me\.items"
    echo

    echo "=== [PVE-F-032] what insertNodes throws on, and what it mutates ==="
    find_in "$W/panel/ConfigPanel.js" "the insertNodes guards" \
        "itemId already exists|id already exists|item\.header = false|item\.groups\.shift\(\)"
    echo

    echo "=== [PVE-F-033] groups are descended into, never created ==="
    sed -n '279,326p' "$W/panel/ConfigPanel.js" 2>/dev/null \
        | grep -nE "while \(Ext\.isArray|findChild|break|appendChild|leaf: true" \
        || gone "the group-descent loop in panel/ConfigPanel.js"
    echo "--- and what a real group item looks like (node 'System'):"
    find_in "$W/node/Config.js" "a group item with its own card" \
        "itemId: 'services'|expandedOnInit: true|groups: \['services'\]"
    echo

    echo "=== [PVE-F-034] resource-tree type to config-panel class ==="
    find_in "$W/Workspace.js" "the treeTypeToClass map" \
        "^ *(root|node|qemu|lxc|storage|sdn|network|pool|tag): '|pvePanelConfig"
    echo

    echo "=== [PVE-F-050] a method with no 'permissions' is root@pam-only ==="
    if [ -f "$TP/pve-access-control/src/PVE/RPCEnvironment.pm" ]; then
        sed -n '/sub check_api2_permissions/,/^}/p' \
            "$TP/pve-access-control/src/PVE/RPCEnvironment.pm"
    else
        gone "RPCEnvironment.pm"
    fi
    echo

    echo "=== [PVE-F-051] register_method's path rules, and fragmentDelimiter ==="
    find_in "$TP/pve-common/src/PVE/RESTHandler.pm" "the registration guards" \
        "duplicate path|path match error|duplicate method definition|method name already defined|fragmentDelimiter"
    echo
} > "$out"

echo "wrote $out"
